---
name: Default Template
about: The default template.
title: ''
labels: ''
assignees: ''

---
<!--
This is **ONLY** used for problems with SolarThing documentation or requests to add more examples for something that you know is not documented.
Please use [wildmountainfarms/solarthing/issues](https://github.com/wildmountainfarms/solarthing/issues) for all issues relating to SolarThing or to ask for general support.
-->

